apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:


- path: src 
  contents:

  - path: debs/iftop
    # fetches iftop deb package 
    http:
      # asset URL (required)
      url: http://archive.ubuntu.com/ubuntu/pool/universe/i/iftop/iftop_1.0~pre4-4_amd64.deb
      # verification checksum (optional)
      sha256: "a509db288bd71dfb79ad7e9af7c93691a6cb598cbef29f1a6ef89ec2fd3ba102"

  - path: debs/wireguard-tools
    http:
      # asset URL (required)
      url: http://launchpadlibrarian.net/491841725/wireguard-tools_1.0.20200513-1~18.04.2_amd64.deb 
      # verification checksum (optional)
      sha256: "71343e1d6f66dabae98234b9e0e3ba516f14cb9ac764bd691f69b606d5153003"
